frr version 10.5.4_git
frr defaults traditional
hostname enterprise-r1
!
interface eth1
 ip address 192.168.12.1/30
exit
!
interface loopback0
 ip address 10.10.0.1/24
exit
!
ip prefix-list PERMIT-ALL seq 5 permit 0.0.0.0/0 le 32
!
router bgp 65001
 neighbor 192.168.12.2 remote-as 65002
 !
 address-family ipv4 unicast
  network 10.10.0.0/24
  neighbor 192.168.12.2 prefix-list PERMIT-ALL in
  neighbor 192.168.12.2 prefix-list PERMIT-ALL out
 exit-address-family
exit
!
end
