frr version 10.5.4_git
frr defaults traditional
hostname enterprise-r1
!
ip prefix-list PERMIT-ALL seq 5 permit 0.0.0.0/0 le 32
ip prefix-list ALLOWED-REDIST seq 5 permit 10.10.0.0/24
!
route-map REDISTRIBUTE-LAN permit 10
 match ip address prefix-list ALLOWED-REDIST
exit
!
interface eth1
 ip address 192.168.12.1/30
exit
!
interface eth2
 ip address 192.168.12.6/30
exit
!
router bgp 65001
 neighbor 192.168.12.2 remote-as 65002
 !
 address-family ipv4 unicast
  redistribute ospf route-map REDISTRIBUTE-LAN
  neighbor 192.168.12.2 prefix-list PERMIT-ALL in
  neighbor 192.168.12.2 prefix-list PERMIT-ALL out
 exit-address-family
exit
!
router ospf
 network 192.168.12.4/30 area 0
 default-information originate always
exit
!
