frr version 10.5.4
frr defaults traditional
hostname enterprise-lan1
!
interface eth1
 ip address 10.20.1.2/30
!
interface eth2
 ip address 10.10.0.1/24
!
router ospf
 network 10.20.1.0/30 area 0
 network 10.10.0.0/24 area 0
!
line vty
!