frr version 10.5.4
frr defaults traditional
hostname enterprise-r2
log syslog informational
!
interface eth1
 ip address 10.20.0.2/30
!
interface eth2
 ip address 10.20.1.1/30
exit
interface loopback0
 ip address 10.0.0.2/32
!
router ospf
 network 10.20.0.0/30 area 0
 network 10.20.1.0/30 area 0
 network 10.0.0.2/32 area 0
!
line vty
!
router bgp 65001
 neighbor 10.0.0.1 remote-as 65001
 neighbor 10.0.0.1 update-source loopback0
exit
