frr version 10.5.4
frr defaults traditional
hostname enterprise-lan1
!
interface eth1
 ip address 192.168.12.5/30
!
interface lan0
 ip address 10.10.0.1/24
!
router ospf
 network 192.168.12.4/30 area 0
 network 10.10.0.0/24 area 0
!
line vty
!
